language: php

cache:
  apt: true
  directories:
    - vendor
    - lib
    - $HOME/.composer/cache

php:
  - 5.5.9
  - 5.5
  - 5.6
  #  Currently 7.+ and hhvm dont support xdebug
  # - 7.0
  # - nightly
  # - hhvm

before_install:
  # Install Java 8
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get update
  - sudo apt-get install -y oracle-java8-installer
  
  # Set and check Java version
  - sudo update-java-alternatives --set java-8-oracle
  - java -version

install:
  - if [ ! -d "lib/stanford-ner-2015-04-20" ]; then
      wget http://nlp.stanford.edu/software/stanford-ner-2015-04-20.zip;
      unzip stanford-ner-2015-04-20.zip -d lib/;
    fi
  - composer install --no-interaction --prefer-source
  - composer create-project wp-coding-standards/wpcs:dev-master --no-dev -n standards/wpcs
  - ./vendor/bin/phpcs -vvv -w --config-set installed_paths '../../../standards/gios/,../../../standards/wpcs/'

before_script:
  - mkdir coverage
  - printf "TestSolrApiUrl=http://jilliantessa.me:8983/solr/gios-dev/select\nStanfordNerPath=lib/stanford-ner-2015-04-20/\n" > config.conf

script:
  - vendor/bin/phpunit # --coverage-clover /tmp/coverage/clover.xml
  - vendor/bin/phpspec run -c .phpspec.yml
  - vendor/bin/phpcs --standard=GIOS --ignore= ./src ./test

after_script:
  - vendor/bin/phpcov merge --clover coverage.xml coverage
  - php vendor/bin/coveralls -v
